### ISSUE TITLE
Dynamic loading

### ISSUE THREAD

**Issue by Erior** [KaGaMiLinAlfa/SharpCompressLoadProblem#1]
Hi

Your problem seems to be that you target .NET Core 3.1 while SharpCompress only gives you 
net462
netstandard2.0
netstandard2.1
net6.0
net7.0

And it picks the 7.0 for you

You would either need to force it to netstandard 2.1 or target one of the prebuild ones.

You could test to apply the following change on your tree.
(copy to project root and run git appl target_net60.txt)

[target_net60.txt](https://github.com/KaGaMiLinAlfa/SharpCompressLoadProblem/files/12666007/target_net60.txt)

**Comment by KaGaMiLinAlfa** [comment]
> 你好
> 
> 你的问题似乎是你以.NET Core 3.1为目标，而SharpCompress只给你net462 netstandard2.0 netstandard2.1 net6.0 net7.0
> 
> 它会为您选择 7.0
> 
> 你要么需要强制它达到 netstandard 2.1，要么以预构建版本之一为目标。
> 
> 您可以测试在树上应用以下更改。 （复制到项目根目录并运行 git appl target_net60.txt）
> 
> [target_net60.txt](https://github.com/KaGaMiLinAlfa/SharpCompressLoadProblem/files/12666007/target_net60.txt)

Thank you very much!
I actually didn't notice the lack of support for 3.1. Following your method, it indeed works properly !
I can't believe I only realized such a simple issue just now

Thanks again for your response!
